### ISSUE TITLE
增加对网关的支持

### ISSUE THREAD

**Issue by SikaiGGMU** [daxingplay/home-assistant-vaillant-plus#19]
目前新产品网关接入后，只能控制生活热水功能，不能产生供暖的实体

**Comment by daxingplay** [comment]
你用的是哪个产品啊？正常的话应该是能显示供暖的实体。你找到 Integrations 里这个集成，然后点下图里的 device，截图看看里面的内容（只用截 control 部分的就行）。
![image](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/173016/c08bd972-fc25-46a2-858e-6ae5e0476687)


在 control 这里应该有两个。
![image](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/173016/0e20da5d-8ede-4e29-a18b-318d9d6fc5f3)

**Comment by SikaiGGMU** [comment]
![IMG_2230](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/105181949/3b1fe5ef-4689-4b9f-bdcc-0c12cbf0ed8e)
![IMG_2229](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/105181949/80799303-c496-4b4c-b650-1bacc5d295a2)

用的新的网关的产品。familyCONNECT

**Comment by SikaiGGMU** [comment]
![Uploading IMG_2231.png…]()

**Comment by daxingplay** [comment]
你用的是这个吗？https://vaillant.cn/product/vsmart-pro-3026/

**Comment by SikaiGGMU** [comment]
vsmart坏了  换了一个新产品 (https://vaillant.cn/product/iot-control/)

**Comment by daxingplay** [comment]
理论上应该也支持。你的HA是哪个版本的呢？

**Comment by SikaiGGMU** [comment]
最新的2024.2.2版本，其实是支持的，只是climate的实体没有产生出来

**Comment by SikaiGGMU** [comment]
Missing required attribute to setup Vaillant Climate. skip.

**Comment by daxingplay** [comment]
> ![IMG_2230](https://private-user-images.githubusercontent.com/105181949/305354372-3b1fe5ef-4689-4b9f-bdcc-0c12cbf0ed8e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzY5ODcsIm5iZiI6MTcwODEzNjY4NywicGF0aCI6Ii8xMDUxODE5NDkvMzA1MzU0MzcyLTNiMWZlNWVmLTQ2ODktNGI5Zi1iZGNjLTBjMTJjYmYwZWQ4ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMDIyNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJhOTlmNzJjOTI2MjZlZjk5MWY0MjgzNDM0NTY0NzZjNWEwNTg3OThjYjljYzY0MmUxNzU4MWVhNzU2ODY3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AlxXfDNgXG42aOZaLg9Haa80iS42rCVtduuH9_kNuTM) ![IMG_2229](https://private-user-images.githubusercontent.com/105181949/305354387-80799303-c496-4b4c-b650-1bacc5d295a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzY5ODcsIm5iZiI6MTcwODEzNjY4NywicGF0aCI6Ii8xMDUxODE5NDkvMzA1MzU0Mzg3LTgwNzk5MzAzLWM0OTYtNGI0Yy1iNjUwLTFiYWNjNWQyOTVhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwMjI0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2ViMzA1ZGFlNjNhODI1ZTU4OTY3NDQxZmUwYTg2YTFhYzM5NWRlNjIwZGU5MDdhYTgwZDJiY2NhMGM2YjZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ucHMQEgVlbcxLvohuyqZsI9WLyWl5mfl5_PvEhEw10Y)
> 
> 用的新的网关的产品。familyCONNECT

最后一个图，传感器下面应该还有一个诊断，能截图看看么？

**Comment by SikaiGGMU** [comment]
![Uploading IMG_2240.png…]()

**Comment by daxingplay** [comment]
> ![Uploading IMG_2240.png…]()
> 
> 

图片没传上来

**Comment by SikaiGGMU** [comment]
![IMG_2240](https://github.com/daxingplay/home-assistant-vaillant-plus/assets/105181949/6a5e00f0-d425-4db9-bbb4-2793c8b296d3)

**Comment by daxingplay** [comment]
感觉你这个网关返回的数据比 vsmart 少了一些，你添加集成的时候提示有几个设备呢？你可以再添加一下，看看设备列表有几个，但不用真添加。

**Comment by SikaiGGMU** [comment]
**只有一个**

**Comment by SikaiGGMU** [comment]
求支持

**Comment by SikaiGGMU** [comment]
求支持

**Comment by daxingplay** [comment]
你在集成页面里把这个集成的调试日志打开，等采集一段时间后，把一些敏感信息去掉发给我吧。

**Comment by piscesbody** [comment]
可以

> 你在集成页面里把这个集成的调试日志打开，等采集一段时间后，把一些敏感信息去掉发给我吧。

大佬，可以集成一下威能家的接口吗？我有个水魔方想接进来。https://vaillant.cn/product/elocirc-app-18816/

**Comment by YaleJian** [comment]
大佬，我的也是只有一个生活热水控制，买的就是叫威能网关
<img width="1083" alt="image" src="https://github.com/daxingplay/home-assistant-vaillant-plus/assets/17241277/98d0c9d0-543c-4cd4-aead-5094e1fa39c5">

**Comment by daxingplay** [comment]
> 大佬，我的也是只有一个生活热水控制，买的就是叫威能网关
> 
> <img width="1083" alt="image" src="https://github.com/daxingplay/home-assistant-vaillant-plus/assets/17241277/98d0c9d0-543c-4cd4-aead-5094e1fa39c5">
> 
> 

好的，我想想办法支持一下吧。主要是我没这个网关设备，我只有威精灵。可能得辛苦你们多帮我测一下了

**Comment by YaleJian** [comment]
需要啥配合的随时联系我，wx：yalejian2020，感谢🙏

**Comment by elwinchen1986** [comment]
[vaillant_plus.zip](https://github.com/user-attachments/files/17788727/vaillant_plus.zip)

在基础上修改了一版，只支持网关，感兴趣的可以自己拿去使用

**Comment by elwinchen1986** [comment]
https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制
<img width="307" alt="image" src="https://github.com/user-attachments/assets/2f599489-8560-43af-9815-c6106dbc39ba">

**Comment by daxingplay** [comment]
> https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制
> 
> <img width="307" alt="image" src="https://github.com/user-attachments/assets/2f599489-8560-43af-9815-c6106dbc39ba">
> 
> 

感谢。我看看怎么合并进来，实现威精灵和新的网关都支持

**Comment by YaleJian** [comment]
坐等合并更新

**Comment by piscesbody** [comment]
`日志记录器: aiohttp.server
来源: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
首次出现: 14:32:26 (3 次总计出现)
上次记录: 14:57:27

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vaillant_plus/config_flow.py", line 73, in async_step_user
    device_list = await client.get_device_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/vaillant_plus_cn_api/api.py", line 168, in get_device_list
    model_alias=d["modelInfo"]["aliasName"],
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable`

![image](https://github.com/user-attachments/assets/fc828b72-1f07-472a-bef0-f5c56fc9d0eb)
登陆就提示这个，日志里头报错这么说的。

**Comment by daxingplay** [comment]
> `日志记录器: aiohttp.server
> 
> 来源: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
> 
> 首次出现: 14:32:26 (3 次总计出现)
> 
> 上次记录: 14:57:27
> 
> 
> 
> Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
> 
>     return await func(self, request, *args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
> 
>     return await super().post(request, flow_id)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
> 
>     return await method(view, request, data, *args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
> 
>     result = await self._flow_mgr.async_configure(flow_id, data)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
> 
>     result = await self._async_configure(flow_id, user_input)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
> 
>     result = await self._async_handle_step(
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         flow, cur_step["step_id"], user_input
> 
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>     )
> 
>     ^
> 
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
> 
>     result: _FlowResultT = await getattr(flow, method)(user_input)
> 
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/vaillant_plus/config_flow.py", line 73, in async_step_user
> 
>     device_list = await client.get_device_list()
> 
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/vaillant_plus_cn_api/api.py", line 168, in get_device_list
> 
>     model_alias=d["modelInfo"]["aliasName"],
> 
>                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^
> 
> TypeError: 'NoneType' object is not subscriptable`
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/fc828b72-1f07-472a-bef0-f5c56fc9d0eb)
> 
> 登陆就提示这个，日志里头报错这么说的。
> 
> 


威精灵还是新的网关？

**Comment by SikaiGGMU** [comment]
> https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制 <img alt="image" width="307" src="https://private-user-images.githubusercontent.com/34827717/390288312-2f599489-8560-43af-9815-c6106dbc39ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDg5NjksIm5iZiI6MTczNDM0ODY2OSwicGF0aCI6Ii8zNDgyNzcxNy8zOTAyODgzMTItMmY1OTk0ODktODU2MC00M2FmLTk4MTUtYzYxMDZkYmMzOWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDExMzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjRkZDY2Mzk0YTlmZTA0MDA2MDA2OGE3OGM1ZTc4YmI2MGNiMTY3MzA2MjUxYmMzNmMwODZmNTdiYzAzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Xd312p5dIDrkizHdPc4FReDz8U-crKYbIV-LBvq61M">

大佬 我发现新的集成不会自动更新数据，需要手动reload集成才能更新数据

**Comment by BlueQWQ** [comment]
> https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制 <img alt="image" width="307" src="https://private-user-images.githubusercontent.com/34827717/390288312-2f599489-8560-43af-9815-c6106dbc39ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTEzMjMsIm5iZiI6MTczNjM5MTAyMywicGF0aCI6Ii8zNDgyNzcxNy8zOTAyODgzMTItMmY1OTk0ODktODU2MC00M2FmLTk4MTUtYzYxMDZkYmMzOWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzdlOGQxZjhiOWZjYTUwNDU2YTMyNjU1ZTQ2NWU0MDA4YjBkZTg1OGMwNTIwNTUzMzAyNWFiYTUxYzdkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HAr453j51vSFTACAR0-OhVbCemV5hrM5KRiH730tP58">

请问一下你的这个版本怎么使用，我也用的是familyconnect

**Comment by elwinchen1986** [comment]
> > https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制 <img alt="image" width="307" src="https://private-user-images.githubusercontent.com/34827717/390288312-2f599489-8560-43af-9815-c6106dbc39ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDg5NjksIm5iZiI6MTczNDM0ODY2OSwicGF0aCI6Ii8zNDgyNzcxNy8zOTAyODgzMTItMmY1OTk0ODktODU2MC00M2FmLTk4MTUtYzYxMDZkYmMzOWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDExMzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjRkZDY2Mzk0YTlmZTA0MDA2MDA2OGE3OGM1ZTc4YmI2MGNiMTY3MzA2MjUxYmMzNmMwODZmNTdiYzAzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Xd312p5dIDrkizHdPc4FReDz8U-crKYbIV-LBvq61M">
> 
> 大佬 我发现新的集成不会自动更新数据，需要手动reload集成才能更新数据

[vaillant_plus.zip](https://github.com/user-attachments/files/18448150/vaillant_plus.zip) 更新了代码，之前的需要配合修改api才可以，新版不需要了，直接可用

**Comment by elwinchen1986** [comment]
> > https://github.com/elwinchen1986/home-assistant-vaillant-plus 在大佬的基础上改了一个版本，不知道怎么提交代码，网关设备已经支持控制 <img alt="image" width="307" src="https://private-user-images.githubusercontent.com/34827717/390288312-2f599489-8560-43af-9815-c6106dbc39ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTEzMjMsIm5iZiI6MTczNjM5MTAyMywicGF0aCI6Ii8zNDgyNzcxNy8zOTAyODgzMTItMmY1OTk0ODktODU2MC00M2FmLTk4MTUtYzYxMDZkYmMzOWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAyNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzdlOGQxZjhiOWZjYTUwNDU2YTMyNjU1ZTQ2NWU0MDA4YjBkZTg1OGMwNTIwNTUzMzAyNWFiYTUxYzdkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HAr453j51vSFTACAR0-OhVbCemV5hrM5KRiH730tP58">
> 
> 请问一下你的这个版本怎么使用，我也用的是familyconnect

[vaillant_plus.zip](https://github.com/user-attachments/files/18448150/vaillant_plus.zip) Copy custom_components/vaillant_plus into your Home Assistant config directory.

**Comment by alone24** [comment]
请问下HA里网关的暖气设置温度和当前温度有什么区别啊？

**Comment by daxingplay** [comment]
> 请问下HA里网关的暖气设置温度和当前温度有什么区别啊？

截个图看看你说的具体是哪里？

**Comment by daxingplay** [comment]
> > 请问下HA里网关的暖气设置温度和当前温度有什么区别啊？
> 
> <img width="458" height="440" alt="Image" src="https://github.com/user-attachments/assets/b33ea100-9077-4a2c-94eb-6804f5fb65ed" /> 这两个地方没区别

用的网关还是威精灵啊？手机App上是怎么显示的呢？
