### ISSUE TITLE
大佬，我账户里面有网关了，但是还是登陆的时候抛出错误。

### ISSUE THREAD

**Issue by piscesbody** [daxingplay/home-assistant-vaillant-plus#28]
日志: aiohttp.server
来源: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
首次发生: 17:18:06 (3 全部发生)
上次记录: 17:19:55

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py", line 199, in factory
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 295, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vaillant_plus/config_flow.py", line 73, in async_step_user
    device_list = await client.get_device_list()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vaillant_plus_cn_api/api.py", line 168, in get_device_list
    model_alias=d["modelInfo"]["aliasName"],
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by daxingplay** [comment]
啥样的网关？这个和网关应该没关系，应该是不支持你账号里的某种设备。

**Comment by simon-the-samoyed** [comment]
@piscesbody 抱歉拖了这么久，这个问题现在定位并修复了。

你这条日志的最后一行和 #27 是同一个错误：

```
vaillant_plus_cn_api/api.py:168  model_alias=d["modelInfo"]["aliasName"]
TypeError: 'NoneType' object is not subscriptable
```

原因不在登录，登录其实是成功的。问题出在随后读取设备列表：云端对本集成无法识别的设备类型（你账号里的 eloCIRC 循环水魔方）会返回 `"modelInfo": null`，而依赖库直接取了下级字段，于是整个设备列表解析失败——**哪怕账号里还有支持的网关设备也一样起不来**。这就是为什么你后来加了网关仍然报错。同时因为这个异常没有被配置流程捕获，HA 只显示了一个笼统的错误，看起来像是登录失败。

已修复并发布：

* 依赖库 [vaillant-plus-cn-api 2.0.1](https://github.com/daxingplay/vaillant-plus-cn-api/releases/tag/v2.0.1)：无法识别的设备会以空的型号信息返回，不再影响整个列表。
* 集成 [v1.2.8](https://github.com/daxingplay/home-assistant-vaillant-plus/releases/tag/v1.2.8)：依赖上述版本。

麻烦在 HACS 里升级到 v1.2.8 并重启 HA，然后重新添加集成试试。注意 eloCIRC 循环水魔方本身仍然不被支持（不会出现对应实体），但它不会再阻止你的网关设备接入了。升级后如果还有问题，请贴出日志，我们继续看。
